### ISSUE TITLE
Wrong symbols for multi-storey brackets

### ISSUE THREAD

**Issue by Mercury13** [notofonts/math#44]
### Title 
Wrong symbols for multi-storey brackets

### Font 
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: this repo, beta branch
Date: 2023-03-15

### Font Version
2.539

### OS name and version
W10 22H2 (IDK other OS)

### Application name and version
Probably all apps

### Issue
Symbols for multi-storey brackets do not construct those brackets, even approximately
  1. For example, write 23B0 <enter> 23B1
  2. Hook and hook
  3. Should be a two-storey curly bracket

For this all parts of multi-storey bracket should be carefully placed.
1. Extensions should protrude a bit beyond OS/2 size.
2. The rest (e.g. parenthesis hooks 239B/9D) should be within OS/2 size.
3. And that should really be a part of large bracket/integral/sum.

### Character data
U+2320 top half integral
U+2321 bottom half integral
U+239B left parenthesis upper hook
…
U+23B3 summation bottom

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/233956926-c1a091c7-96f0-4191-88a9-405f8786e75c.png)

**Comment by simoncozens** [comment]
I'm not convinced that this is true. It's not ideal but at the same time it's not wrong; trying to do math typesetting without using a math typesetting engine is just going to end up in frustration, so I don't think the font should support that.

**Comment by dscorbett** [comment]
These characters are meant for terminal-based math layout without a dedicated math typesetting engine. If the font doesn’t support terminal-based math layout, it shouldn’t include these characters, but it seems simple enough to fix them and keep them in the font.

U+23B0 UPPER LEFT OR LOWER RIGHT CURLY BRACKET SECTION and U+23B1 UPPER RIGHT OR LOWER LEFT CURLY BRACKET SECTION are different from the rest because they might not need to connect across lines; see https://github.com/be5invis/Iosevka/issues/1089#issuecomment-850897381.

**Comment by khaledhosny** [comment]
I don’t this belongs to Noto Sans Math. Such uses should be supported by Noto Sans Mono or Noto Sans Symbols. I’d rather drop these code points from Noto Sans Math and keep the glyphs solely for use in MATH table glyph assemblies.
