### ISSUE TITLE
Inconsistent kerning

### ISSUE THREAD

**Issue by Enivex** [notofonts/math#73]
Noto sans math
![image](https://github.com/notofonts/math/assets/2191754/0772a46f-7157-4a0d-ab1e-e4a441723b6f)

Fira math
![image](https://github.com/notofonts/math/assets/2191754/66ff92ef-75b2-4d8a-b213-e03581f0e359)

**Comment by khaledhosny** [comment]
Noto is spaced to avoid collisions (try `(j)` with both fonts) at the expense of spacing. The way math engines work is you have to sacrifice one for the other. Uniform spacing is less important in math since symbols are used as isolated entities not runs of text. You should compare it with more math fonts.

**Comment by Enivex** [comment]
> Noto is spaced to avoid collisions (try `(j)` with both fonts) at the expense of spacing. The way math engines work is you have to sacrifice one for the other. Uniform spacing is less important in math since symbols are used as isolated entities not runs of text. You should compare it with more math fonts.

Fair enough! I'll compare with some other fonts.

**Comment by khaledhosny** [comment]
I think this issue should be closed, the existing spacing is intentional and consistent with other math fonts.
