### ISSUE TITLE
Unbalanced spacing in fractions

### ISSUE THREAD

**Issue by Enivex** [notofonts/math#74]
Noto Sans Math
![image](https://github.com/notofonts/math/assets/2191754/97a1450c-da5b-45ca-910b-592a99025101)

As you can see, the numerator is much further from the line than the denominator. For comparison:

Fira Math
![image](https://github.com/notofonts/math/assets/2191754/1b241dee-620a-4a44-be2e-94d88b60a6ad)

**Comment by khaledhosny** [comment]
Are you testing display mode or inline? In display mode there is typically more space so that numerators in equations like `\frac{1}{2} \frac{1y}{2}` remain aligned:

Noto Sans Math:
<img width="134" alt="image" src="https://github.com/notofonts/math/assets/93914/ed3588d6-a28c-4ab1-9fd6-f6a896bd9507">

Fira Math:
<img width="134" alt="image" src="https://github.com/notofonts/math/assets/93914/4c7fcc4a-5323-48e0-82b0-427a4ec84798">

You can also check other math fonts.

**Comment by Enivex** [comment]
> In display mode there is typically more space

I agree that that what Fira Math is doing is suboptimal, but in this case Noto Sans Math does seem to have quite a bit more asymmetric spacing than other fonts

From left to right:
New Computer Modern Math -> Stix Two Math -> Noto Sans Math
![comparison](https://github.com/notofonts/math/assets/2191754/11c81aaa-08e7-4e37-bd17-c5b117fe9b00)

**Comment by khaledhosny** [comment]
It took a bit of fiddling since too many constants are at the play here, but I think the end result is better now.

Noto Sans Math with #76:
<img width="668" alt="image" src="https://github.com/notofonts/math/assets/93914/bc058db9-5cfa-4d86-a68f-7b61e9ff09a9">


Computer Modern Math (TFM fonts):
<img width="668" alt="image" src="https://github.com/notofonts/math/assets/93914/a23be57d-f509-41e7-885e-baf9e1b052c7">

Cambria Math:
<img width="668" alt="image" src="https://github.com/notofonts/math/assets/93914/f0db980c-b810-4592-b7aa-86e98a65f49c">

STIX Two Math:
<img width="668" alt="image" src="https://github.com/notofonts/math/assets/93914/b83d2cfc-362f-4383-b26b-4f2ce140b59a">

Fira Math:
<img width="668" alt="image" src="https://github.com/notofonts/math/assets/93914/68b309c4-49a5-485d-9621-74df73103770">

**Comment by simoncozens** [comment]
Fira seems to shift stuff upwards when there's a descender in the numerator.

**Comment by khaledhosny** [comment]
Yes, but that is undesired, you want fraction in these cases to align. The new constants make the gabs above and below look balanced without breaking the alignment.
