### ISSUE TITLE
Some vertical variants have variants themselves

### ISSUE THREAD

**Issue by mpsmath** [notofonts/math#86]
### Font 
NotoSansMath-Regular.ttf

### Where the font came from, and when
  >   Site: https://github.com/notofonts/math/releases/tag/NotoSansMath-v3.000
  >   Date: 2024-06-14

### Font Version
v3.000

### Issue
For some glyphs that has vertical variants, the last variant has itself variants that point back to earier variants. This can lead to a loop when the typesetting engine shall choose variant.

### Character data
I have seen this for U+27E8, U+27E9, U+2991 and U+2992. All of them in the last variant .s20. (I have not made a complete check of other glyphs.) After more investigations it turns out that the fraction U+2044 has as a first variant the  "fraction" (itself!) and then go to "slash", "slash.s01" and so on. But the "slash" itself has its own variants.

**Comment by khaledhosny** [comment]
> I have seen this for U+27E8, U+27E9, U+2991 and U+2992. All of them in the last variant .s20.

This is a bug indeed, but it should be harmless. When checking for variants, the engine should always check only the base glyph for variants, not the variants themselves (this is not TFM where the variants are a linked list with each glyph linking to the next variant).



> After more investigations it turns out that the fraction U+2044 has as a first variant the "fraction" (itself!)

All variants start with the base glyph itself, otherwise (some) engines will always skip it and try the first variant. I don’t see what is wrong with this.


> and then go to "slash", "slash.s01" and so on. But the "slash" itself has its own variants.

This is intentional. I want to re-use the slash variants for the fraction, and as said above the fact that a variant has variants itself should not be an issue.
