### ISSUE TITLE
Extender part `uni0305.s00` has endConnectorLength 0

### ISSUE THREAD

**Issue by mkorje** [notofonts/math#94]
The glyph for `U+0305` has glyph parts in the GlyphAssembly table in MATH to allow for constructing an overline accent of any size.

Currently, Noto Sans Math has two glyph parts with the glyph `uni0305.s00`. The first is not an extender, and has startConnectorLength 0 and endConnectorLength 417. The second is an extender, and has startConnectorLength 417 and endConnectorLength 0. The second, as it is an extender, is what gets repeated when constructing a larger sized accent. But because the endConnectorLength is 0, the part is then taken to not have a connector on that end. The spec mentions the below:

> If the part does not have a connector on one of its ends, the corresponding connector length should be set to zero.

**Comment by simoncozens** [comment]
To be honest I think the reason SILE, Firefox and LuaTeX get this right, and Typst does not, is because Typst is not correctly interpreting the spec.

> But because the endConnectorLength is 0, the part is then taken to not have a connector on that end.

Right, but we've also said that the whole glyph is a connector on its left side. "Connector" here just means "a straight bit you can overstrike".

What the values say is: You set `uni0305` first. `uni0305` has 417 units of straight line (the whole thing) on its right side, so you will be fine if you overstrike the next glyph by any amount between 0 and 417 units on the right hand side; then you set `uni0305.s00` next to it as many times as you like, and to make it fit the width, you can eat up any amount of space from the previous glyph between 0 and 417 units. In other words, the whole thing is a straight line and you can overstrike it wherever you like.

I see in https://github.com/typst/typst/issues/5283 that there are gaps between the overlines. But step one of assembling glyph assemblies is to set the glyphs with *maximum overlaps* and then extend the connectors until you reach the desired width. There's no way that glyphs with zero sidebearings should ever produce gaps.

**Comment by khaledhosny** [comment]
I agree this is a bug in Noto Sans Math (the end connector should not be zero), but I also think Typst is doing something wrong here. I’m going to fix the end connector either way.
